model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 1024
  image_size: 448
  end_sym: "</s>"
  llama_model: "/home/rramosprof22/emotion-llama-testing/checkpoints/Llama-2-7b-chat-hf"

  ckpt: "/home/rramosprof22/emotion-llama-testing/checkpoints/minigptv2_checkpoint.pth"

  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16


datasets:    
  feature_face_caption: 
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 30

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  # init_lr: 1e-5
  # min_lr: 8e-5
  # warmup_lr: 1e-6

  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  # init_lr: 1e-6
  # min_lr: 1e-6
  # warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 30
  num_workers: 6
  # iters_per_epoch: 5000
  iters_per_epoch: 1000


  warmup_steps: 1000

  seed: 42
  output_dir: "/home/rramosprof22/emotion-llama-testing/checkpoints/save_checkpoint"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 2
  dist_url: "env://"
  distributed: True

  wandb_log: False
  job_name: minigptv2_finetune
